name: Run JAR Action

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: npm install

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run JAR runner
        id: run-jar
        uses: 'AleksandraAleksandrova/jar-runner-action@main'
